version: '3.8'
services:
  k6_low:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts 
      - ./test-results:/results
    command: run -e MY_HOSTNAME=host.docker.internal:5000 /scripts/low.js
  k6_mid:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts 
      - ./test-results:/results
    command: run -e MY_HOSTNAME=host.docker.internal:5000 /scripts/mid.js
  k6_high:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts 
      - ./test-results:/results
    command: run -e MY_HOSTNAME=host.docker.internal:5000 /scripts/high.js

